#!/usr/bin/env python3
"""A mechanical ceiling on how much of this site depends on one company.

SOURCES tasks 1-2 (collector_providers.py's own-quote precedence, and two
rounds of second-comparison-feed probing that came back all-blocked -- see
that file's own docstring) exist because every incumbent-provider price
used to come from exactly one place: Wise's comparison feed. That is still,
today, the single biggest source on this site -- Wise supplies both the
comparison feed AND its own precedence-ranked quote (collector_providers.py
names it explicitly: "Wise its own quote API"). Nothing in tasks 1-4 makes
that number zero. What this gate makes sure of is that it does not creep
UP again on some future PR that adds a provider by simply extending the
comparison panel, undoing the actual point of tasks 1-2 and 3 (multi-venue
stablecoin pricing) without anyone noticing -- the same "nothing automated
ever looked at the diff" gap .github/workflows/checks.yml's own header
describes for PR #160, applied to a source-diversity regression instead of
a deleted chart.

DEFINITION. Of every priced row in data/providers_latest.json (own,
comparison or measured -- "missing" rows carry no price and are excluded,
same as tools/emit_source_meter.py's own denominator), how many trace back
to Wise as the single external company behind the number:
  - every "comparison" row (the feed itself IS Wise's v4/comparisons API --
    see collector.py's fetch_baseline and collector_providers.py's
    docstring; there is no other comparison feed in this repo today)
  - every "own" row where the provider IS Wise (its own v3/quotes API,
    still the same company, just a different endpoint)
Stablecoin ("measured") rows and every OTHER provider's own quote
(Instarem, Airwallex, ...) are never Wise-dependent by this definition.

    wise_share = wise_rows / (own_rows + comparison_rows + measured_rows)

The committed ceiling lives in tools/wise_share_baseline.json. This script
fails the PR if the CURRENT tree's wise_share exceeds that ceiling by more
than a floating-point rounding tolerance. It is not regenerated by a normal
run; see --update-baseline. Same shape as tools/check_inventory.py's
page_inventory.json gate, applied to a share instead of a count, and to a
ceiling (must not RISE) instead of a floor (must not FALL).

Usage:
  python3 tools/check_wise_share.py                  # check vs committed ceiling
  python3 tools/check_wise_share.py --update-baseline  # OVERWRITE the ceiling
      with the current tree's share. Run explicitly, review the diff,
      commit deliberately. Never run as part of a normal check.
  python3 tools/check_wise_share.py --show           # print the current
      tree's share without touching the baseline file.

Stdlib only.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROVIDERS_LATEST = os.path.join(HERE, "data", "providers_latest.json")
BASELINE_PATH = os.path.join(HERE, "tools", "wise_share_baseline.json")
WISE_COMPANY_NAME = "Wise"
# A rounding tolerance, not a real allowance: floats accumulate drift across
# json.dump/json.load round trips and this gate must not flap on that.
EPSILON = 1e-9


def compute_share(doc=None):
    """-> (wise_rows, total_priced_rows, share) from data/providers_latest.json.

    Pure given `doc`; reads the file itself only when `doc` is omitted, so
    this is testable offline against a hand-built fixture.
    """
    if doc is None:
        if not os.path.exists(PROVIDERS_LATEST):
            return 0, 0, 0.0
        with open(PROVIDERS_LATEST) as f:
            doc = json.load(f)

    own = comparison = measured = wise_own = 0
    for corridor in (doc.get("corridors") or {}).values():
        for size in (corridor.get("sizes") or {}).values():
            for r in size.get("rows") or []:
                src = r.get("source")
                if src == "own":
                    own += 1
                    if r.get("provider") == WISE_COMPANY_NAME:
                        wise_own += 1
                elif src == "comparison":
                    comparison += 1
                elif src == "measured":
                    measured += 1
                # "missing" rows carry no price -- excluded from the
                # denominator, same as the source meter's own definition.

    total = own + comparison + measured
    wise_rows = comparison + wise_own
    share = (wise_rows / total) if total else 0.0
    return wise_rows, total, share


def load_baseline():
    if not os.path.exists(BASELINE_PATH):
        return None
    with open(BASELINE_PATH) as f:
        return json.load(f)


def write_baseline(wise_rows, total, share):
    doc = {
        "wise_share_ceiling": share,
        "wise_rows": wise_rows,
        "total_priced_rows": total,
        "note": ("Generated by tools/check_wise_share.py --update-baseline. "
                 "A future PR that raises wise_share above this ceiling "
                 "fails the checks.yml gate; lowering it is always fine and "
                 "this file should be re-generated (not hand-edited) when "
                 "it does."),
    }
    with open(BASELINE_PATH, "w") as f:
        json.dump(doc, f, indent=2, sort_keys=True)
        f.write("\n")


def main():
    show = "--show" in sys.argv
    update = "--update-baseline" in sys.argv

    wise_rows, total, share = compute_share()

    if show:
        print(f"  wise_rows={wise_rows} total_priced_rows={total} "
              f"wise_share={share:.6f}")
        return

    if update:
        write_baseline(wise_rows, total, share)
        print(f"  wrote {os.path.relpath(BASELINE_PATH, HERE)}: "
              f"ceiling set to {share:.6f} ({wise_rows}/{total})")
        return

    baseline = load_baseline()
    if baseline is None:
        print("  [error] no tools/wise_share_baseline.json committed -- "
              "run --update-baseline once, review, and commit it",
              file=sys.stderr)
        sys.exit(1)

    ceiling = baseline["wise_share_ceiling"]
    if total == 0:
        print("  [warn] no priced rows in data/providers_latest.json -- "
              "nothing to check, treating as pass")
        return

    if share > ceiling + EPSILON:
        print(
            "  FAIL: single-company (Wise) share of published prices rose\n"
            f"    was:  {ceiling:.4%}  ({baseline.get('wise_rows')}/{baseline.get('total_priced_rows')})\n"
            f"    now:  {share:.4%}  ({wise_rows}/{total})\n"
            "  This PR increases how much of the site depends on one\n"
            "  external company. If that is deliberate (a new provider\n"
            "  onboarded through the Wise comparison feed rather than its\n"
            "  own quote, say), re-run tools/check_wise_share.py "
            "--update-baseline,\n  review the diff, and commit it explicitly.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"  wise_share ok: {share:.4%} ({wise_rows}/{total}), "
          f"ceiling {ceiling:.4%}")


if __name__ == "__main__":
    main()
