#!/usr/bin/env python3
"""A mechanical gate against the site quietly losing charts, tables, or
interactive controls.

PR #160 ("D3: how it works rewrite...") deleted the homepage's waterfall
chart and its full corridor comparison table while calling itself a
rewrite. It was later reverted, by a person noticing, after the fact. This
script exists so noticing is no longer the job of a person scrolling the
diff -- it is a CI gate, decided by a machine, the same way tools/check_page.py
already is for jargon and broken renders.

It re-derives, from the page source (markup + inline script -- charts and
tables on this site are as often built by a JS template string as they are
static markup, see index.html's renderWaterfall), a per-page inventory of:
  - charts  (an <svg>/<canvas> with real content, or a JS function that
             builds one as an HTML string and injects it)
  - tables  (a literal <table>, or the site's own "repeating row" idiom --
             sending-money.html's .prow rows, the-index.html's .gap-row /
             .wrow, fee-tiers.html's .breakdown-row -- none of which use a
             literal <table> tag)
  - interactive elements (a select, a real button that changes what's shown
             -- a route/amount pill, a country/currency chip picker, a
             "show everything" expander -- never a plain nav link)

and compares it, item by item, against the committed baseline in
page_inventory.json. It fails loudly if any page's count DROPPED. Growing,
or staying the same, is expected and always allowed -- future phases add
sections, they should never need to touch this file except with
--update-baseline, deliberately, reviewed in a diff.

The baseline (page_inventory.json as committed) was generated from commit
7078efd09 -- the last commit before PR #160 landed, i.e. the fullest
known-good state of the site before the regression this gate exists to
catch. It is not regenerated by a normal run of this script; see
--update-baseline below.

Usage:
  python3 tools/check_inventory.py                 # check current tree vs baseline
  python3 tools/check_inventory.py --update-baseline  # OVERWRITE the baseline
      with the current tree's inventory. Run explicitly, review the diff,
      commit deliberately. Never run as part of a normal check.
  python3 tools/check_inventory.py --show           # print the current
      tree's inventory without touching the baseline file, for inspection.

Stdlib only.
"""

import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASELINE_PATH = os.path.join(HERE, "page_inventory.json")

# Small decorative/icon svgs (a magnifier, an arrow-in-a-circle, the little
# paper-plane on the ask button) are not charts. On this site every real
# chart's <svg> is either sized well past icon scale in the markup, or has
# no static width/height at all because it is built entirely as an HTML
# string by JS and injected via innerHTML -- see index.html's
# renderWaterfall. An icon's <svg ... width="16" height="16" ...> is the
# one shape this rule needs to exclude.
_ICON_WH = re.compile(r'width="(\d+)"\s+height="(\d+)"')


def _is_icon_svg(tag_text):
    m = _ICON_WH.search(tag_text)
    if not m:
        return False
    w, h = int(m.group(1)), int(m.group(2))
    return w <= 24 and h <= 24


_FUNC_DEF = re.compile(r"function\s+([A-Za-z_]\w*)\s*\([^)]*\)\s*\{")


def _matching_brace(src, open_pos):
    """Index just past the `{` at `open_pos`'s matching `}`, brace-counting.

    Not comment/string aware -- good enough for this codebase's style
    (plain JS, no braces inside its single-quoted HTML-string literals);
    worst case it over- or under-attributes a chart/table to the wrong
    function name, which is cosmetic, not a miscount (dedup keys are
    still distinct enough not to collapse two real items into one).
    """
    depth = 0
    for i in range(open_pos, len(src)):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    return len(src)


def _enclosing_function(src, pos):
    """Name of the innermost `function NAME(...) { ... }` whose body
    actually contains `pos` -- brace-matched, not just "nearest name
    that appears earlier in the file" (which would misattribute a call
    sitting after a function definition but outside its body)."""
    best = None
    for m in _FUNC_DEF.finditer(src, 0, pos + 1):
        if m.start() > pos:
            break
        close = _matching_brace(src, m.end() - 1)
        if m.end() - 1 <= pos < close:
            best = m.group(1)  # innermost wins: later matches replace it
    return best


def _strip_noise(src):
    """Drop comments so a dead example in a comment doesn't get counted."""
    return re.sub(r"(?s)<!--.*?-->", " ", src)


def find_charts(src, page):
    items = []
    seen_ids = set()

    # (a) a real, non-icon <svg ...> or <canvas ...> element with an id --
    # corridor.html's placeholder <svg id="wf">, <svg id="hist"> that its
    # own drawWaterfall()/drawHistory() fill in.
    for tag in ("svg", "canvas"):
        # (?<!['"]) excludes a tag that is actually a JS string literal
        # (e.g. '<svg viewBox="...">' + ...) -- that is pass (b)'s job,
        # keyed by the function that builds it, not counted here as if it
        # were a second, separate static element.
        for m in re.finditer(r"(?<![\"'])<" + tag + r"\b[^>]*>", src):
            tag_text = m.group(0)
            if tag == "svg" and _is_icon_svg(tag_text):
                continue
            idm = re.search(r'id="([\w-]+)"', tag_text)
            ident = idm.group(1) if idm else f"{tag}@{m.start()}"
            if ident in seen_ids:
                continue
            seen_ids.add(ident)
            items.append(f"chart: <{tag} id=\"{ident}\">")

    # (b) a chart built entirely as an HTML string and injected -- the
    # renderWaterfall/renderCostCurve/renderFeatured/renderLiveCard idiom.
    # One chart per function that contains a "<svg ..." string literal,
    # not one per literal (a bar loop can emit several).
    seen_funcs = set()
    for m in re.finditer(r"['\"]<svg\b", src):
        fn = _enclosing_function(src, m.start())
        key = fn or f"anon@{m.start()}"
        if key in seen_funcs:
            continue
        seen_funcs.add(key)
        items.append(f"chart: function {fn}()" if fn else "chart: inline svg builder")

    # (c) the site's shared sparkline chart library (js/chart.js's
    # MarginChart -- see index.html's own comment on it), called on a
    # target container rather than built inline. index.html, country.html
    # (twice -- the country's own chart and the independent-reference gap
    # chart), the-index.html, ask.html each call it once per chart.
    for m in re.finditer(r"MarginChart\.render\(", src):
        # Only look inside this one call's own argument list -- up to its
        # closing ");" -- so a getElementById target belonging to some
        # later, unrelated call can never be picked up as this chart's name.
        end = src.find(");", m.end())
        tail = src[m.end():end if end != -1 else m.end() + 160]
        idm = re.search(r"getElementById\(\s*['\"]([\w-]+)['\"]", tail)
        if idm:
            ident = f"marginchart:{idm.group(1)}"
            label = f"chart: MarginChart on #{idm.group(1)}"
        else:
            fn = _enclosing_function(src, m.start())
            ident = f"marginchart:{fn or m.start()}"
            label = (f"chart: MarginChart in function {fn}()" if fn
                      else "chart: MarginChart render call")
        if ident in seen_ids:
            continue
        seen_ids.add(ident)
        items.append(label)

    return items


# Literal-table naming key: prefer id, then class.
def _table_key(tag_text):
    idm = re.search(r'id="([\w-]+)"', tag_text)
    if idm:
        return "id", idm.group(1)
    cm = re.search(r'class="([\w-]+)', tag_text)
    if cm:
        return "class", cm.group(1).split()[0]
    return None, None


# Repeating-row idiom: a class ending "-row" (fee-tiers.html's
# .breakdown-row, the-index.html's .gap-row), the bare site convention
# "*row" (the-index.html's .wrow), or the site's own "prow"/"prow-hdr"
# (sending-money.html). A "-hdr" variant is the header of the same table,
# not a second one, so it collapses onto the same base name.
# No trailing `"` required -- sending-money.html's row class is built as
# '<div class="prow'+(isMissing?' missing':'')+'">', so the literal source
# text right after class=" is just "prow" with no closing quote anywhere
# nearby; anchoring on one would silently stop matching the day a class
# got a conditional modifier appended, which is exactly the kind of
# ordinary refactor that must not look like this feature disappearing.
ROW_CLASS = re.compile(r'class=\\?["\']([\w-]*row[\w-]*)')


def find_tables(src, page):
    items = []
    seen = set()

    for m in re.finditer(r"(?<![\"'])<table\b[^>]*>", src):
        kind, key = _table_key(m.group(0))
        ident = f"{kind}:{key}" if key else f"table@{m.start()}"
        if ident in seen:
            continue
        seen.add(ident)
        items.append(f"table: <table {kind}=\"{key}\">" if key else "table: <table>")

    # A table built as an HTML string (index.html's renderCorridorTable,
    # corridor.html's drawLadder) -- same rule as charts, one per function.
    # Skipped if it targets a class this file already counted above (the
    # same table baked statically for no-JS AND re-rendered by JS onto the
    # same element -- one logical table, e.g. index.html's
    # #corridorTableSection).
    seen_funcs = set()
    static_keys = {key for kind, key in
                   (_table_key(t.group(0)) for t in
                    re.finditer(r"(?<![\"'])<table\b[^>]*>", src))
                   if key}
    for m in re.finditer(r"['\"]<table\b", src):
        # A short tail window, not `[^'\"]*` cut at the attribute value's
        # own quote -- '<table class="corridor-table">' has that class
        # name sitting right after a `"`, which a naive "stop at any
        # quote" scan would slice off before ever reading it.
        tail = src[m.end():m.end() + 120]
        cm = re.search(r'class=\\?["\']?([\w-]+)', tail)
        if cm and cm.group(1) in static_keys:
            continue
        fn = _enclosing_function(src, m.start())
        key2 = fn or f"anon@{m.start()}"
        if key2 in seen_funcs:
            continue
        seen_funcs.add(key2)
        items.append(f"table: function {fn}()" if fn else "table: inline table builder")

    # Repeating-row structures with no literal <table> tag at all.
    bases = {}
    for m in ROW_CLASS.finditer(src):
        cls = m.group(1)
        base = re.sub(r"-hdr$", "", cls)
        bases.setdefault(base, cls)
    for base, example in bases.items():
        ident = f"row:{base}"
        if ident in seen:
            continue
        seen.add(ident)
        items.append(f"table-like rows: class=\"{example}\"")

    return items


# Interactive: a real control that changes what a reader sees. Never a
# plain <a> nav link, and never the hamburger nav-toggle (that changes the
# nav, not the page's content).
SELECT_ID = re.compile(r'<select\b[^>]*id="([\w-]+)"')
BUTTON_ID = re.compile(r'<button\b[^>]*id="([\w-]+)"')
# A button whose class marks it as a picker/pill/chip/toggle, in static
# markup or in a JS string literal building one (machine-room.html's
# per-currency chip, sending-money.html's route-pill / amount pill).
# nav-toggle is excluded explicitly -- it opens the hamburger nav, which
# changes the nav, not the page's content.
BUTTON_CLASS = re.compile(
    r"<button\b[^>]*class=\\?\"?([\w-]*(?:pill|chip|toggle)[\w-]*)"
)
NAV_TOGGLE_CLASSES = {"nav-toggle"}


def find_interactive(src, page):
    items = []
    seen = set()

    for m in SELECT_ID.finditer(src):
        ident = m.group(1)
        if ident in seen:
            continue
        seen.add(ident)
        items.append(f"interactive: <select id=\"{ident}\">")

    for m in BUTTON_ID.finditer(src):
        ident = m.group(1)
        if ident == "navToggle" or ident in seen:
            continue
        seen.add(ident)
        items.append(f"interactive: <button id=\"{ident}\">")

    for m in BUTTON_CLASS.finditer(src):
        cls = m.group(1)
        if cls in NAV_TOGGLE_CLASSES:
            continue
        ident = f"class:{cls}"
        if ident in seen:
            continue
        seen.add(ident)
        items.append(f"interactive: button class=\"{cls}\"")

    return items


PAGE_CATEGORIES = {
    "charts": find_charts,
    "tables": find_tables,
    "interactive": find_interactive,
}


def real_pages():
    """Every top-level *.html file in the repo -- the site's actual reader
    -facing surface, not a subdirectory of generated weekly snapshots
    (w/*.html), not a hardcoded guess."""
    return sorted(
        os.path.basename(p)
        for p in glob.glob(os.path.join(HERE, "*.html"))
    )


def inventory_for(path):
    with open(path, encoding="utf-8") as f:
        src = _strip_noise(f.read())
    page = os.path.basename(path)
    out = {}
    all_items = []
    for cat, fn in PAGE_CATEGORIES.items():
        items = fn(src, page)
        out[cat] = len(items)
        all_items.extend(items)
    out["items"] = sorted(all_items)
    return out


def build_inventory():
    inv = {}
    for page in real_pages():
        inv[page] = inventory_for(os.path.join(HERE, page))
    return inv


def load_baseline():
    if not os.path.exists(BASELINE_PATH):
        return None
    with open(BASELINE_PATH, encoding="utf-8") as f:
        return json.load(f)


def compare(baseline, current):
    """Return a list of human-readable shrinkage failures, empty if none."""
    fails = []
    for page, base_counts in baseline.items():
        cur_counts = current.get(page)
        if cur_counts is None:
            fails.append(f"{page}: page is GONE (was in the baseline inventory)")
            continue
        for cat in ("charts", "tables", "interactive"):
            b, c = base_counts.get(cat, 0), cur_counts.get(cat, 0)
            if c < b:
                fails.append(
                    f"{page}: {cat} shrank {b} -> {c} "
                    f"(baseline: {base_counts.get('items', [])}; "
                    f"current: {cur_counts.get('items', [])})"
                )
        base_items = set(base_counts.get("items", []))
        cur_items = set(cur_counts.get("items", []))
        missing = base_items - cur_items
        if missing and not any(cat_fail.startswith(f"{page}: ") for cat_fail in fails):
            # Counts can tie even when the actual items differ (one lost,
            # one gained) -- still worth surfacing, just not as a hard
            # failure on its own unless a count also dropped above.
            pass
    return fails


def main(argv):
    if "--show" in argv:
        print(json.dumps(build_inventory(), indent=2, sort_keys=True))
        return 0

    if "--update-baseline" in argv:
        inv = build_inventory()
        with open(BASELINE_PATH, "w", encoding="utf-8") as f:
            json.dump(inv, f, indent=2, sort_keys=True)
            f.write("\n")
        print(f"wrote {BASELINE_PATH} from the current tree "
              f"({len(inv)} pages). Review this diff before committing.")
        return 0

    baseline = load_baseline()
    if baseline is None:
        print(f"no baseline at {BASELINE_PATH} -- nothing to check against. "
              f"Run --update-baseline once, deliberately, to create it.")
        return 1

    current = build_inventory()
    fails = compare(baseline, current)

    total_pages = len(baseline)
    print(f"checked {total_pages} pages against page_inventory.json's baseline")
    if not fails:
        print("no page shrank charts, tables, or interactive elements vs baseline. ok")
        return 0

    print(f"\n{len(fails)} SHRINKAGE FAILURE(S):")
    for f in fails:
        print("  - " + f)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
